---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: app
    image: nginx
    resources:
      requests:
        memory: "600Mi"
        cpu: "100m"
      limits:
        memory: "6100Mi"
        cpu: "200m"
