---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-no-constraint
  labels:
    app: nginx1
spec:
  replicas: 20
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
      - name: nginx
        image: nginx:1.15
        resources:
          requests:
            cpu: 300m
            memory: 456Mi
        ports:
        - containerPort: 80
